# try-finally보다는 try-with-resources를 사용하라
## try-finally
전통적으로 자원이 제도로 닫힘을 보장하는 수단으로 try-finally가 쓰였다. 그러나 이는 두 개의 close가 필요한 객체를 생성할 경우 try-finally가 중첩되어야 하는 경우가 많다.
또한 try-finally 문에서 예외는 try와 finally 모두 발생할 수 있는데 이렇게 되면 마지막 에러만 개발자가 알 수 있고 다른 에러는 알 수 없다. 정작 중요한 에러는 첫 번째 에러일 가능성이 높기 때문이다.
## try-with-resources
그래서 등장한 문법이 try-with-resources이다. 
```java
try(Scanner scanner = new Scanner(System.in);
        PrintWriter writer = new PrintWriter(System.out)) {
    ...
}
```
이렇게 try() 안에 자원을 넣어주면 try가 끝나는 시점에 자동으로 close()를 호출해준다. 또한 try-with-resources는 try와 finally 모두에서 예외가 발생하면 try에서 발생한 예외를 기록하고, finally에서 발생한 예외는 숨긴다.
그렇다고 숨겨진 예외를 볼 수 없는 것 또한 아니다. Throwable에 추가된 getSuppressed 메서드를 이용하면 숨겨진 예외도 알 수 있게 된다.
catch 문도 쓸 수 있어 다수의 예외 처리도 가능하다.

## 결론
자원을 회수하는 최선의 방법은 try-with-resources를 사용하는 것이다. 코드도 더 짧고 분명해지고 예외 정보도 훨씬 유용하다. try-finally는 더 이상 자원을 회수하는 최선의 방법이 아니다.